name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm test -- --run
      - run: npm run build

  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      DATABASE_URL: sqlite+pysqlite:///./ci.db
      APP_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip
      - run: pip install .[dev]
      - run: ruff check .
      - run: mypy app
      - run: bandit -r app -ll
      - run: pytest -q

  docker:
    name: Docker images
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    steps:
      - uses: actions/checkout@v4
      - name: Build api image
        run: docker build -t scouthouse-api ./backend
      - name: Build web image
        run: docker build -t scouthouse-web ./frontend
